# Generated by Django 6.0.5 on 2026-05-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_id_alter_post_id_alter_tag_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Django Blog', help_text='Displayed in the navbar and footer.', max_length=100)),
                ('tab_title', models.CharField(default='Django Blog', help_text='Used as the browser tab suffix: "Post Title | Django Blog".', max_length=100)),
                ('tagline', models.CharField(default='Ideas worth sharing.', help_text='Hero heading shown to guest visitors on the homepage.', max_length=200)),
                ('hero_subtext', models.TextField(default='A community blog where writers share stories, tutorials, and insights on any topic.', help_text='Supporting paragraph under the hero heading.')),
                ('about_title', models.CharField(default='About Django Blog', help_text='Heading displayed at the top of the About page.', max_length=200)),
                ('about_content', models.TextField(blank=True, help_text='Full body of the About page. Supports rich text (HTML).')),
                ('posts_per_page', models.PositiveSmallIntegerField(default=5, help_text='Number of posts shown per page on the homepage and list views.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
